/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.snowflake.snowflake.ingest.sdk)
    api(libs.io.github.cdimascio.dotenv.java)
    api(libs.net.snowflake.snowflake.jdbc)
    api(libs.com.ibm.icu.icu4j)
    api(libs.com.nimbusds.nimbus.jose.jwt)
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.org.apache.httpcomponents.httpclient)
    api(libs.commons.codec.commons.codec)
    api(libs.org.apache.httpcomponents.httpasyncclient)
    api(libs.javax.xml.bind.jaxb.api)
    api(libs.org.apache.arrow.arrow.vector)
    api(libs.io.dropwizard.metrics.metrics.core)
    api(libs.io.dropwizard.metrics.metrics.jvm)
    api(libs.io.dropwizard.metrics.metrics.jmx)
    runtimeOnly(libs.org.apache.arrow.arrow.memory.netty)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.slf4j.slf4j.simple)
    testImplementation(libs.org.powermock.powermock.module.junit4)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.powermock.powermock.api.mockito2)
    testImplementation(libs.org.powermock.powermock.core)
    compileOnly(libs.org.slf4j.slf4j.api)
}

group = "com.snowflake.streaming.app"
version = "1.0-SNAPSHOT"
description = "java-streaming"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
